name: Deploy PROD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{variables.HEROKU_EMAIL}}
          heroku_app_name: ${{variables.HEROKU_APP_NAME_PROD}}
        env:
          HD_APP_ENV: prod
          HD_APP_SECRET: ${{secrets.APP_SECRET_PROD}}
          HD_JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY_PROD}}
          HD_JWT_PUBLIC_KEY: ${{secrets.JWT_PUBLIC_KEY_PROD}}
          HD_JWT_PASSPHRASE: ${{secrets.JWT_PASSPHRASE_PROD}}